[project]
name = "meta2fdp"
version = "0.1.0"
description = "Adapters between source systems and a FAIR Data Point for publishing metadata."
readme = "README.md"
authors = [
    { name = "Karolis Cremers", email = "k.m.p.cremers@lumc.nl" },
    { name = "Anna Niehues", email = "a.niehues@lumc.nl" }
]
requires-python = ">=3.12"
dependencies = [
    "keyring>=25.7.0",
    "pandas>=3.0.1",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "rdflib>=7.6.0",
    "requests>=2.32.5",
    "sempyro>=2.1.0",
]

[project.scripts]
meta2fdp = "meta2fdp:main"

[build-system]
requires = ["uv_build>=0.10.4,<0.11.0"]
build-backend = "uv_build"

[tool.pytest]
minversion = "9.0"
testpaths = [
    "tests",
]
addopts = [
    "-ra",
]
norecursedirs = ["__pycache__"]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "ruff>=0.15.2",
]
