[project]
name = "meta2fdp"
version = "0.1.0"
description = "Adapters between source systems and a FAIR Data Point for publishing metadata."
readme = "README.md"
authors = [
    { name = "Karolis Cremers", email = "k.m.p.cremers@lumc.nl" },
    { name = "Anna Niehues", email = "a.niehues@lumc.nl" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
meta2fdp = "meta2fdp:main"

[build-system]
requires = ["uv_build>=0.10.4,<0.11.0"]
build-backend = "uv_build"
