FDP: # labels of environment variables containing secrets:
  URL: ephemeralFDP #used as URL to interact with and keyring service name
  username: ephemeralFDPusername
  parent_resource_purl: parent_resource_purl
