mode: 
  replace: False
  publish: True

SQL: # labels of environment variables containing secrets:
  server_name: server_name
  database_name: database_name
  username: username
  keyring_service: keyring_service
  catalog_id: catalog_id
  dataset_id: dataset_id

FDP: # labels of environment variables containing secrets:
  URL: ephemeralFDP #used as URL to interact with and keyring service name
  username: ephemeralFDPusername
  parent_resource_purl: parent_resource_purl

FDP:
  URL: URL
  PURL: PURL  # should end with /
  catalog_purl: catalog_purl
  