theme: http://publications.europa.eu/resource/authority/data-theme/HEAL
license:
langtags:

contactPoint:
  contactPoint_email:
  contactPoint_name:

publisher:
  publisher_name_en:
  publisher_name_nl:
  publisher_email:
  publisher_identifier:
  publisher_url:

langtags: en,nl