file_paths:
  catalog_input_file: catalog_input_file
  dataset_input_file: datasets_input_file
  distribution_input_file: 
  dataservice_input_file: 
  datasetseries_input_file: 

mapping:
  catalog:
    title: title
    description: description
    applicable_legislation: 
    geographical_coverage: 
    temporal_coverage: 
    homepage: 

  dataset:
    title: title
    description: description
    identifier: identifier
    theme: theme
    license: license
    access_rights: access_rights
    keyword: 
    applicable_legislation: 
    number_of_records: numberOfRecords
    number_of_unique_individuals: numberOfUniqueIndividuals

  contactPoint:
    hasEmail: contactPoint_email
    formatted_name: contactPoint_name

  publisher:
    name: publisher_name
    mbox: publisher_email
    identifier: publisher_identifier
    homepage: publisher_url
    country: publisher_country
    publishertype: 
    publishernote: 

  creator:
    name: creator_name
    mbox: creator_email
    identifier: creator_identifier
    homepage: creator_url
    country: creator_country

  author:
    name: author_name
    hasEmail: author_email
    identifier: author_identifier
    homepage: author_url
    country: author_country
    role: author_role
